LineageOS-20-nashc:
  kernel:
    - git clone https://github.com/anuragpindoriya/android_kernel_realme_mt6785_howwof.git -b lineage-20
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 lineage-nashc_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - nashc
  kernelSU:
    - stable-pin

Zenitsu-nashc:
  kernel:
    - git clone https://github.com/Killerpac/android_kernel_realme_mt6785 -b openela
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 lineage-nashc_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - nashc
  kernelSU:
    - stable-pin

DivestOS-13-nashc:
  kernel:
    - git clone https://github.com/HowWof/android_kernel_realme_mt6785.git -b divest-13
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 lineage-nashc_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - nashc
  kernelSU:
    - stable-pin
  
S20-FE-5G:
  kernel:
    - git clone https://github.com/anuragpindoriya/android_kernel_samsung_sm8250.git -b stable
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 r8q_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - s20FE5G
  kernelSU:
    - stable
  NeedNoneKernelSUVarient:
    - false

Moto-g52:
  kernel:
    - git clone https://github.com/anuragpindoriya/android_kernel_motorola_sm6225_tom.git -b t
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 lineageos_rhode_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - s20FE5G
  kernelSU:
    - stable
  
Redmi-note-10s:
  kernel:
    - git clone https://github.com/anuragpindoriya/android_kernel_xiaomi_rosemary.git -b 14.0
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 rosemary_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - s20FE5G
  kernelSU:
    - stable

Redmi-note-10s-lineage:
  kernel:
    - git clone https://github.com/LineageOS/android_kernel_xiaomi_mt6785.git -b lineage-21
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 rosemary_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - s20FE5G
  kernelSU:
    - stable

Redmi-note-10s-AndroDesk:
  kernel:
    - git clone https://github.com/AndroDesk/android_kernel_xiaomi_rosemary.git -b lineage-21
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 rosemary_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image
  anykernel:
    - s20FE5G
  kernelSU:
    - stable
  

Clean:
  out:
    - rm -rf out
    - rm -rf KernelSU
    - rm -rf drivers/kernelsu
  kernel:
    - make mrproper
  custom:
    - git status

# Stable-pin version of KernelSU is used by KernelSU.sh to replace placeholder (kernelsu-version) with the newest stable version from ksu_version.txt
KernelSU:
  version:
    stable-pin:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s kernelsu-version
    stable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
    unstable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

AnyKernel3:
  version:
    nashc:
      - git clone https://github.com/HowWof/AnyKernel3.git -b master
    s20FE5G:
      - git clone https://github.com/anuragpindoriya/AnyKernel3.git -b devices/s20FE5g
    test:
      - echo "Test Success!"
